# Ex1 - Filtering and Sorting Data



### Step 1. Import the necessary libraries

In [12]:
import numpy as np
import pandas as pd

### Step 2. Import the dataset from this [address](https://raw.githubusercontent.com/justmarkham/DAT8/master/data/chipotle.tsv).

In [13]:
# URL donde se encuentra el dataset
url = "https://raw.githubusercontent.com/justmarkham/DAT8/master/data/chipotle.tsv"

### Step 3. Assign it to a variable called chipo.

In [14]:
# Importamos el dataset.
# sep='|' indica que las columnas están separadas por |
chipo = pd.read_csv(url, sep='\t')

chipo

,order_id,quantity,item_name,choice_description,item_price
0,1,1,Chips and Fresh Tomato Salsa,NaN,$2.39
1,1,1,Izze,[Clementine],$3.39
2,1,1,Nantucket Nectar,[Apple],$3.39
3,1,1,Chips and Tomatillo-Green Chili Salsa,NaN,$2.39
4,2,2,Chicken Bowl,"[Tomatillo-Red Chili Salsa (Hot), [Black Beans...",$16.98
...,...,...,...,...,...
4617,1833,1,Steak Burrito,"[Fresh Tomato Salsa, [Rice, Black Beans, Sour ...",$11.75
4618,1833,1,Steak Burrito,"[Fresh Tomato Salsa, [Rice, Sour Cream, Cheese...",$11.75
4619,1834,1,Chicken Salad Bowl,"[Fresh Tomato Salsa, [Fajita Vegetables, Pinto...",$11.25
4620,1834,1,Chicken Salad Bowl,"[Fresh Tomato Salsa, [Fajita Vegetables, Lettu...",$8.75
4621,1834,1,Chicken Salad Bowl,"[Fresh Tomato Salsa, [Fajita Vegetables, Pinto...",$8.75

# Name of the max valued product

In [11]:
# 1. PRODUCTO CON MAYOR PRECIO UNITARIO

# Calculamos el precio de una unidad dividiendo
# el precio total de la línea entre la cantidad comprada
chipo["unit_price"] = chipo["item_price"] / chipo["quantity"]

# Buscamos el índice del producto con mayor precio unitario
# y mostramos su nombre
chipo.loc[chipo["unit_price"].idxmax(), "item_name"]

TypeError: unsupported operand type(s) for /: 'str' and 'int'

In [ ]:
#de manera comprimida

chipo.loc[chipo["item_price"].idxmax(), "item_name"]

'Steak Salad Bowl'

3598    Chips and Fresh Tomato Salsa
Name: item_name, dtype: object

                         item_name
3598  Chips and Fresh Tomato Salsa

'Chips and Fresh Tomato Salsa'

### Step 4. How many products cost more than $10.00?

31

### Step 5. What is the price of each item? 
###### print a data frame with only two columns item_name and item_price

                         item_name  item_price
3598  Chips and Fresh Tomato Salsa       44.25
3480                 Carnitas Bowl       35.25
1254               Chicken Burrito       35.00
3602               Chicken Burrito       35.00
3601                Veggie Burrito       33.75
...                            ...         ...
3936                   Canned Soda        1.09
2922                 Bottled Water        1.09
1396                   Canned Soda        1.09
2562                   Canned Soda        1.09
1457                   Canned Soda        1.09

[4622 rows x 2 columns]

### Step 6. Sort by the name of the item

,order_id,quantity,item_name,choice_description,item_price
3389,1360,2,6 Pack Soft Drink,[Diet Coke],12.98
341,148,1,6 Pack Soft Drink,[Diet Coke],6.49
1849,749,1,6 Pack Soft Drink,[Coke],6.49
1860,754,1,6 Pack Soft Drink,[Diet Coke],6.49
2713,1076,1,6 Pack Soft Drink,[Coke],6.49
...,...,...,...,...,...
2384,948,1,Veggie Soft Tacos,"[Roasted Chili Corn Salsa, [Fajita Vegetables,...",8.75
781,322,1,Veggie Soft Tacos,"[Fresh Tomato Salsa, [Black Beans, Cheese, Sou...",8.75
2851,1132,1,Veggie Soft Tacos,"[Roasted Chili Corn Salsa (Medium), [Black Bea...",8.49
1699,688,1,Veggie Soft Tacos,"[Fresh Tomato Salsa, [Fajita Vegetables, Rice,...",11.25
1395,567,1,Veggie Soft Tacos,"[Fresh Tomato Salsa (Mild), [Pinto Beans, Rice...",8.49

### Step 7. What was the quantity of the most expensive item ordered? 2 ways

V1

15

V2

item_price    44.25
quantity      15.00
dtype: float64

### Step 8. How many times was a Veggie Salad Bowl ordered?

18

### Step 9. How many times did someone order more than one Canned Soda?

20